on: 
    push:
        branches:
          - main
          - "release/**"
        paths:
        # and dart file
          - "**/*.dart" 

    pull_request:
        branches:
          - main
          - "release/**"


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2
